site_name: PYCO
site_url: https://pyco-apps.github.io/
site_author: Liam Collod
site_description: Software for CGI and creatives.
copyright: Copyright &copy; 2024 Liam Collod

docs_dir: 'site'
site_dir: 'build'

theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  font:
    # custom key added in main.html
    extras:
      - Urbanist
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'white'
      accent: 'custom'
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'custom'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: img/logo-nobg.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.top
    - navigation.indexes

# nav is defined by the awesome-pages plugin which use .pages files.

extra:
  # custom key read in main.html
  meta:
    default:
      image: img/social-card.png
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pyco-apps
      name: Pyco on GitHub
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.gamedev.place/@liamcollod
      name: Pyco developer personal Mastodon account
    - icon: simple/gumroad
      link: https://app.gumroad.com/pyco
      name: Gumroad Store
    - icon: simple/discord
      link: https://discord.gg/47ySGqMEAj
      name: Discord Server

extra_css:
  - extra.css

plugins:
  - search
  - privacy
  - awesome-pages
  - redirects:
      redirect_maps:
        'store.md': 'https://app.gumroad.com/pyco'
        'software/standalone-colorspace-converter/docs/index.md': 'software/standalone-colorspace-converter/docs/getting-started.md'
        # backward-compat of structure before 09/09/24; we deleted docs/
        'docs/index.md': 'software/index.md'
        'docs/standalone-colorspace-converter/index.md': 'software/standalone-colorspace-converter/index.md'
        'docs/standalone-colorspace-converter/developer.md': 'software/standalone-colorspace-converter/docs/developer.md'
        'docs/standalone-colorspace-converter/features.md': 'software/standalone-colorspace-converter/docs/features.md'
        'docs/standalone-colorspace-converter/getting-started.md': 'software/standalone-colorspace-converter/docs/getting-started.md'
        'docs/standalone-colorspace-converter/linux.md': 'software/standalone-colorspace-converter/docs/linux.md'
        'docs/pointers-gamut-cli/index.md': 'software/pointers-gamut-cli/index.md'
        'docs/pointers-gamut-cli/features.md': 'software/pointers-gamut-cli/docs/features.md'
        'docs/pointers-gamut-cli/getting-started.md': 'software/pointers-gamut-cli/docs/getting-started.md'
        'docs/katana-texture-monitor/index.md': 'software/katana-texture-monitor/index.md'
        'docs/katana-texture-monitor/developer.md': 'software/katana-texture-monitor/docs/developer.md'
        'docs/katana-texture-monitor/features.md': 'software/katana-texture-monitor/docs/features.md'
        'docs/katana-texture-monitor/getting-started.md': 'software/katana-texture-monitor/docs/features.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true